### ISSUE TITLE
Add max width/max height constraints

### ISSUE THREAD

**Issue by cubanismo** [cubanismo/allocator#13]
The prototype code doesn't allow devices to expose their maximum image width and height as a constraint.  Support for this constraint should be added.

**Comment by cubanismo** [comment]
Thinking about this over the weekend, I wonder if we actually need these to be  constraints, or whether the various allocation device drivers should just fail to return capability sets for assertions that are beyond their max width/height?  It's a trivial check, and running it through the capability filtering seems kind of like overkill.  On the other hand, it would be nice if users of the library could discover a device's max width/height somehow.

**Comment by mvicomoya** [comment]
The main problem I see with relying on get_capabilities() failing is that users wouldn't get useful information of what failed. Was the allocation size beyond the limits? Was the format invalid / not supported? Or was any of the specified uses?

Therefore, would it make sense to add a "get_allocation_hints" API that takes the array of uses and then returns a list of hints (max/min size, formats, unsupported/unknown uses, ...)?

**Comment by cubanismo** [comment]
It would be important not to make it too general so it remains clear when to use Capabilities Vs. "Hints", but yes, perhaps specifying usage and asking for possible assertion values or value ranges is a reasonable feature.  Limiting to just those values covered by assertions (which are extensible, so this would have to be as well unfortunately), seems reasonable.

As you notice, we're missing a format enumeration API anyway.  I think "try and fail" was perhaps what people were assuming there too, but that design paradigm tends to spawn the need for verbose debug callbacks and error code explosion, as you allude to.

Querying supported usage itself might be intractable, because it's combinatorial.  While various usages might be supported on a given device by themselves, they may not be supported together.  Seems like EGLConfigs all over again.  I'd rather punt to try-and-fail here personally.  It seems unlikely apps will want to write a general usage solver to use at runtime, nor expose usage to users as a config option, unlike width, height, and format.  For usage, they're more likely to run through a short list of supported usages ordered by preference: Their zero-copy path, their blit fallback, and maybe a CPU-blit ultimate fallback.

**Comment by mvicomoya** [comment]
Yeah, I agree that querying usages wouldn't be desirable. What I actually had in mind when writing my previous comment (but I failed to convey) is that the new API could report which of the given uses was unsupported. However, given that it could be a combination of them, and not a use in particular, I agree it might be better to just fail and let apps try something else.

**Comment by mvicomoya** [comment]
This should be fixed now with 6c9a181bd3a153f1c34f827b54c3d826f825b208
